on:
  push:
    paths:
      - ".github/workflows/*"
  schedule:
    - cron: "0 18 */1 * *"

name: firefox
jobs:
  sync:
    runs-on: self-hosted
    env:
      TZ: Europe/Busingen
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Initialize Environment
        run: |
          rm -rf $PWD/*
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo -E apt-get -qq update
          sudo apt-get install -y mercurial
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean

      - name: Sync Source Code
        run: |
          hg clone https://hg.mozilla.org/mozilla-central/ firefox-source

      - name: Commit Changes
        run: |
          mv firefox-source/* $PWD/ && rm -rf firefox-source
          git config --local user.name "github-action[bot]"
          git config --local user.email "${{ secrets.EMAIL }}"
          git add .
          git commit -am "Update On $(date)"
      
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          
      - name: Healthy Check
        if: (!cancelled())
        run: |
          echo "Check space usage"
          df -hT
          echo "Check memory usage"
          free -m
        
  push:
    runs-on: self-hosted
    env:
      TZ: Europe/Busingen
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set variables
        run: |
          echo "VERSION=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        shell: bash

      - name: Download Binaries
        run: |
          mkdir -p release
          pushd release || exit 1
          # Nightly Version
          wget 'https://download.mozilla.org/?product=firefox-nightly-latest-ssl&os=win64&lang=en-US' -O Firefox-Nightly-amd64.exe
          wget 'https://download.mozilla.org/?product=firefox-nightly-latest-ssl&os=win64-aarch64&lang=en-US' -O Firefox-Nightly-arm64.exe
          wget 'https://download.mozilla.org/?product=firefox-nightly-latest-ssl&os=win&lang=en-US' -O Firefox-Nightly-i386.exe
          wget 'https://download.mozilla.org/?product=firefox-nightly-latest-ssl&os=osx&lang=en-US' -O Firefox-Nightly-amd64.dmg
          wget 'https://download.mozilla.org/?product=firefox-nightly-latest-ssl&os=linux64&lang=en-US' -O Firefox-Nightly-amd64.tar.bz2 
          wget 'https://download.mozilla.org/?product=firefox-nightly-latest-ssl&os=linux&lang=en-US' -O Firefox-Nightly-i386.tar.bz2
          # Latest Stable Version
          wget 'https://download.mozilla.org/?product=firefox-latest-ssl&os=win64&lang=en-US' -O Firefox-amd64.exe
          wget 'https://download.mozilla.org/?product=firefox-latest-ssl&os=win64-aarch64&lang=en-US' -O Firefox-arm64.exe
          wget 'https://download.mozilla.org/?product=firefox-latest-ssl&os=win&lang=en-US' -O Firefox-i386.exe
          wget 'https://download.mozilla.org/?product=firefox-latest-ssl&os=osx&lang=en-US' -O Firefox-amd64.dmg
          wget 'https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64&lang=en-US' -O Firefox-amd64.tar.bz2 
          wget 'https://download.mozilla.org/?product=firefox-latest-ssl&os=linux&lang=en-US' -O Firefox-i386.tar.bz2
          # Beta Version
          wget 'https://download.mozilla.org/?product=firefox-beta-latest-ssl&os=win64&lang=en-US' -O Firefox-Beta-amd64.exe
          wget 'https://download.mozilla.org/?product=firefox-beta-latest-ssl&os=win64-aarch64&lang=en-US' -O Firefox-Beta-arm64.exe
          wget 'https://download.mozilla.org/?product=firefox-beta-latest-ssl&os=win&lang=en-US' -O Firefox-Beta-i386.exe
          wget 'https://download.mozilla.org/?product=firefox-beta-latest-ssl&os=osx&lang=en-US' -O Firefox-Beta-amd64.dmg
          wget 'https://download.mozilla.org/?product=firefox-beta-latest-ssl&os=linux64&lang=en-US' -O Firefox-Beta-amd64.tar.bz2 
          wget 'https://download.mozilla.org/?product=firefox-beta-latest-ssl&os=linux&lang=en-US' -O Firefox-Beta-i386.tar.bz2
          # Developer Edition Version
          wget 'https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=win64&lang=en-US' -O Firefox-Dev-Edition-amd64.exe
          wget 'https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=win64-aarch64&lang=en-US' -O Firefox-Dev-Edition-arm64.exe
          wget 'https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=win&lang=en-US' -O Firefox-Dev-Edition-i386.exe
          wget 'https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=osx&lang=en-US' -O Firefox-Dev-Edition-amd64.dmg
          wget 'https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=linux64&lang=en-US' -O Firefox-Dev-Edition-amd64.tar.bz2 
          wget 'https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=linux&lang=en-US' -O Firefox-Dev-Edition-i386.tar.bz2
          # ESR Version
          wget 'https://download.mozilla.org/?product=firefox-esr-latest-ssl&os=win64&lang=en-US' -O Firefox-ESR-amd64.exe
          wget 'https://download.mozilla.org/?product=firefox-esr-latest-ssl&os=win64-aarch64&lang=en-US' -O Firefox-ESR-arm64.exe
          wget 'https://download.mozilla.org/?product=firefox-esr-latest-ssl&os=win&lang=en-US' -O Firefox-ESR-i386.exe
          wget 'https://download.mozilla.org/?product=firefox-esr-latest-ssl&os=osx&lang=en-US' -O Firefox-ESR-amd64.dmg
          wget 'https://download.mozilla.org/?product=firefox-esr-latest-ssl&os=linux64&lang=en-US' -O Firefox-ESR-amd64.tar.bz2 
          wget 'https://download.mozilla.org/?product=firefox-esr-latest-ssl&os=linux&lang=en-US' -O Firefox-ESR-i386.tar.bz2
          popd || exit 1

      - name: Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ env.VERSION }}
          tag: ${{ env.VERSION }}
          draft: false
          prerelease: false
          artifacts: |
            ./release/*
            
      - name: Delete Older Release
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          repo: bolucat/Firefox
          keep_latest: 1
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
